/**
 * LevelData - Type definitions for level data generated by Claude API
 *
 * These interfaces define the structure of level JSON that describes
 * platforms, collectibles, NPCs, and puzzles for each chapter.
 */

export interface Vector3 {
  x: number;
  y: number;
  z: number;
}

export interface Platform {
  position: Vector3;
  size: Vector3;
  type: 'solid' | 'bouncy';
  color?: string;  // Hex color
  requires_size?: 'small' | 'normal' | 'large';
}

export interface Collectible {
  type: 'key' | 'star' | 'card';
  position: Vector3;
  card_suit?: 'hearts' | 'diamonds' | 'clubs' | 'spades';
  card_value?: number;
}

export interface NPC {
  name: string;
  position: Vector3;
  model_id?: string;
  dialogue: string[];
}

export interface SizePuzzle {
  area_bounds: {
    min: Vector3;
    max: Vector3;
  };
  required_size: 'small' | 'large';
  hint: string;
}

export interface Atmosphere {
  sky_color: string;      // Hex color
  fog_color: string;      // Hex color
  fog_near: number;
  fog_far: number;
  ambient_light: string;  // Hex color
}

export interface LevelData {
  chapter_number: number;
  chapter_title: string;
  setting: string;

  atmosphere: Atmosphere;

  platforms: Platform[];
  collectibles: Collectible[];
  npcs: NPC[];

  spawn_point: Vector3;
  gate_position: Vector3;

  size_puzzles: SizePuzzle[];
}

/**
 * Validate that an object conforms to LevelData structure
 */
export function validateLevelData(data: unknown): data is LevelData {
  if (!data || typeof data !== 'object') return false;

  const level = data as LevelData;

  // Check required fields
  if (typeof level.chapter_number !== 'number') return false;
  if (typeof level.chapter_title !== 'string') return false;
  if (typeof level.setting !== 'string') return false;

  // Check arrays exist
  if (!Array.isArray(level.platforms)) return false;
  if (!Array.isArray(level.collectibles)) return false;
  if (!Array.isArray(level.npcs)) return false;
  if (!Array.isArray(level.size_puzzles)) return false;

  // Check atmosphere
  if (!level.atmosphere || typeof level.atmosphere !== 'object') return false;

  // Check spawn and gate
  if (!isVector3(level.spawn_point)) return false;
  if (!isVector3(level.gate_position)) return false;

  return true;
}

function isVector3(v: unknown): v is Vector3 {
  if (!v || typeof v !== 'object') return false;
  const vec = v as Vector3;
  return typeof vec.x === 'number' &&
         typeof vec.y === 'number' &&
         typeof vec.z === 'number';
}
